### ISSUE TITLE
Ожидаемый результат работы

### ISSUE THREAD

**Issue by perfilov03** [kingdomstay/gf-django-vue#3]
**Лабораторные работы**

- [x] 1 л.р. – frontend проекта _(5 баллов)​_

- [x] 2 л.р. – базовый backend + linter, swagger _(5 баллов)​_

- [x] 3 л.р. – docker, celery, mailhog _(10 баллов)​_

- [x] 4 л.р. –  oauth2, redis (frontend+ backend) _(10 баллов)​_

- [x] 5 л.р. – фикстуры,  центрифуга (frontend+ backend) _(10 баллов)​_

- [x] 6 л.р - логирование _(10 баллов)_

**Дополнительно:**

- [x] _10 баллов_ – ответы на вопросы

**Comment by kingdomstay** [comment]
Оу ес
